/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */

plugins {
    kotlin("jvm") version "1.9.0" apply false
}

allprojects {
    group = "com.pdfmanager"
    version = "1.0.0"

    repositories {
        mavenCentral()
    }
}